default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: "v1.39.1" # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: template\.yaml
  - repo: local
    hooks:
      - id: ty-check
        name: Run ty check
        entry: uvx ty check
        language: system
        types: [python]
        pass_filenames: false # This ensures 'ty check' runs on all relevant files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        name: Ruff (python)
  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--wrap-descriptions", "0"]
