default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: "v0.69.1" # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: template\.yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 (python)
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: ["--wrap-descriptions", "0"]
