AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple Keychain API

Globals:
  Api:
    TracingEnabled: True

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Domain:
        DomainName: api.tliwaka.com.mx
        BasePath:
          - keychain
        CertificateArn: arn:aws:acm:us-east-1:031840582743:certificate/0993a941-2e53-44ed-a765-8a24b5b7e20b
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Main entry point for the Telegram messages
      Runtime: python3.9
      CodeUri: src/
      Handler: keychain.ports.http_inputs.webhook
      Events:
        NewWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
            RestApiId: !Ref MainApi
