AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Keychain Bot Main API definition

Parameters:
  TelegramBotToken:
    Type: String
    Description: Token that will be used to communicate with the Telegram API.
  SecretToken:
    Type: String
    Description: Token to check if the request comes from a valid source.

Globals:
  Api:
    TracingEnabled: True
  Function:
    Environment:
      Variables:
        TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
        SECRET_TOKEN: !Ref SecretToken

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  KeychainLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dist/
      CompatibleRuntimes:
        - python3.13
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Main entry point for the Telegram messages
      Runtime: python3.13
      CodeUri: handlers/
      Handler: service.webhook_handler
      Tracing: Active
      Layers:
        - !Ref KeychainLayer
      Events:
        NewWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
            RestApiId: !Ref MainApi
