AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple Keychain API

Globals:
  Api:
    TracingEnabled: True

Resources:
  MainApi:
    Type: AWS::Serverless::Api
