AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Keychain Bot Main API definition
Globals:
  Api:
    TracingEnabled: True

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  KeychainLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dist/
      CompatibleRuntimes:
        - python3.9
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Main entry point for the Telegram messages
      Runtime: python3.9
      CodeUri: handlers/
      Handler: service.webhook_handler
      Layers:
        - !Ref KeychainLayer
      Events:
        NewWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
            RestApiId: !Ref MainApi
