name: Build and Deploy

on:
  push:
    branches:
      - "main"

env:
  USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  STACK_NAME: keychain_api

jobs:
  build-and-package:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
