name: Build and deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build the main package and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Restoring cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Generate requirements.txt file
        run: poetry export -o requirements.txt
      - name: Create layer directory
        run: mkdir -p dist/python/
      - name: Install dependencies
        run: pip install . -t dist/python/
      - run: sam build --use-container
      - run: |
          sam deploy --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --stack-name KeychainAPI \
                     --s3-bucket ${{ secrets.AWS_SAM_BUCKET }} \
                     --s3-prefix KeychainAPI \
                     --capabilities CAPABILITY_IAM \
                     --region us-east-1 \
                     --parameter-overrides "TelegramBotToken=${{ secrets.BOT_TOKEN }} SecretToken=${{ secrets.API_TOKEN }}"
