name: Code Quality Checks

on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    name: Check code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Restoring cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install
      - name: Check style with flake8
        run: poetry run flake8 tests src
      - name: Check format with black
        run: poetry run black --check tests src
      - name: Check type hinting with mypy
        run: poetry run mypy tests src
  test:
    name: Execute code testing
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Restoring cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install
      - name: Unit & Coverage test
        run: poetry run pytest && poetry run codecov
